apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook
resources:
  - ../../../apps/guestbook/base
images:
  - name: ghcr.io/anatoliy-a/compdev26-guestbook
    digest: sha256:f8f6c3301acc0f0f15674999556bdaf73bf2f4208651cd5f80433db0435faf61
patches:
  - path: patches/serviceaccount.yaml
  - path: patches/configmap.yaml
  - path: patches/httproute.yaml
