apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook
resources:
  - ../../../apps/guestbook/base
images:
  - name: ghcr.io/anatoliy-a/compdev26-guestbook
    digest: sha256:a1034d7c1c5634ac5895c59896e1889137ca542e0d66bbce12caefa4434a272c
patches:
  - path: patches/serviceaccount.yaml
  - path: patches/configmap.yaml
  - path: patches/httproute.yaml
